version: '3.3'

services:
  app:
    image: sample:1.0
    container_name: sample_app
    build: .
    ports: 
      - 80:3000
    environment:
      - MONGO_URI=mongodb://sampledb/sample
    depends_on: 
      - db
    networks: 
      - samplenet
  db:
    image: mongo:3.0.15
    container_name: sample_db
    volumes:
      - ./db:/data/db
    networks:
      samplenet:
        aliases:
          - "sampledb"
networks:
  samplenet:
    driver: bridge
